#!/bin/sh -e
# Prints all desktop files names out
# Requires j4-dmenu-desktop

if [ $# -gt 0 ]
then
    at now <<EOF
        DISPLAY=$DISPLAY j4-dmenu-desktop --dmenu="(cat &> /dev/null) | (echo '$@')"
EOF
fi

PIPE=$(mktemp -u)
mkfifo -m 600 $PIPE
trap "rm $PIPE" EXIT
cat $PIPE &
j4-dmenu-desktop --dmenu="(cat > $PIPE) | (cat << EOF)" &> /dev/null
