#!/bin/bash
# Used to select wifi 
# Requires Network Manager, fzf, font awesome, sed, and bash (Also requires sway however swaymsg commands can be removed; only side effect is window stays on screen till process is finished)

wifi=$(nmcli -f SSID,SECURITY,IN-USE -t d wifi list | sed s_:__g | sed 's_*_ *_' | sed 's_WPA1 WPA2__' | sed 's_WPA2__' | sed 's_WPA__' | sed 's_WEP__' | sed '/^/d' | fzf --prompt="Network: ")

wifi=${wifi%?}

if [ "${wifi: -1}" == " " ]; then

    swaymsg move container scratchpad

    wifi=${wifi%?}

    if [ "${wifi: -1}" == "" ];  then

        wifi=${wifi%?}

    fi

    nmcli connection down "$wifi"

    notify-send "Disconnected from $wifi"

    exit 0
fi

if [ "${wifi: -1}" == "" ];  then

    wifi=${wifi%?}

    con=$(nmcli c show | grep "$wifi")

    if [ -z "$con" ]; then

        read -s -p "Enter Password: " pass

        swaymsg move container scratchpad

        nmcli d wifi connect "$wifi" password "$pass"

        notify-send "Connected to $wifi"

        exit 0

    else

        swaymsg move container scratchpad

        echo "$wifi"

        nmcli c up "$wifi"

        notify-send "Connected to $wifi"

        exit 0

    fi
else

    swaymsg move container scratchpad

    nmcli d wifi connect "$wifi"

    notify-send "Connected to $wifi"

    exit 0

fi

notify-send "Failed to connect to $wifi"

exit 1
