#!/usr/bin/env bash
# Copys password from pass onto clipboard using fzf, requires sway, fzf, pass, wl-clipboard, sed, grep, and bash
cd $HOME/.password-store
PASSFILE=$(tree -Ffi | grep '.gpg' | sed 's/.gpg$//g' | sed 's/^..//' | fzf --color=fg:#F7F7F7,bg:#2b2929,hl:#F7F7F7,fg+:#F7F7F7,bg+:235,hl+:#F7F7F7,bg+:#e95420 --color=info:#2b2929,prompt:#2b2929,spinner:135,pointer:#e95420,marker:#2b2929,gutter:#2b2929 --bind='tab:toggle-down,btab:toggle-up' --border --reverse --inline-info)

if [ -z "$PASSFILE" ]; then
	exit 0
fi

PASSDATA="$(pass $PASSFILE)"
PASS="$(echo "$PASSDATA" | head -n 1)"

swaymsg exec wl-copy $PASS 
