#!/usr/bin/env bash
# Copys password from pass onto clipboard using fzf, requires sway, fzf, pass, wl-clipboard, sed, grep, and bash
cd $HOME/.password-store
PASSFILE=$(tree -Ffi | grep '.gpg' | sed 's/.gpg$//g' | sed 's/^..//' | fzf --color=fg:#F7F7F7,bg:#2b2929,hl:#19B6EE,fg+:#F7F7F7,bg+:235,hl+:81,hl+:#3EB34F --color=info:#F7F7F7,prompt:#e95420,spinner:135,pointer:#e95420,marker:#e95420 --border --reverse --inline-info)

if [ -z "$PASSFILE" ]; then
	exit 0
fi

PASSDATA="$(pass $PASSFILE)"
PASS="$(echo "$PASSDATA" | head -n 1)"

swaymsg exec wl-copy $PASS
