#!/usr/bin/env bash
# Copys password from pass onto clipboard using fzf, requires sway, fzf, pass, wl-clipboard, sed, grep, and bash
cd $HOME/.password-store
PASSFILE=$(tree -Ffi | grep '.gpg' | sed 's/.gpg$//g' | sed 's/^..//' | fzf --color=dark,fg+:#F7F7F7,bg:#181818,hl:#3EB34F --reverse --border --inline-info)

if [ -z "$PASSFILE" ]; then
	exit 0
fi

PASSDATA="$(pass $PASSFILE)"
PASS="$(echo "$PASSDATA" | head -n 1)"

swaymsg exec wl-copy $PASS
