#!/bin/bash
# Creates, delets, and edits entries in pass
# Requires sway, fzf, pass, zenity, find, git, yes sed, grep, and bash 

cd /home/haden/.password-store || return

option=$(echo -e "Add\nDelete\nEdit\nGit" | grep -i 'Add\|Delete\|Edit\|Git' | fzf --prompt="Password Manager: ")

if [ "$option" = "Add" ]; then

    location=$(find . -not -path '*/\.*' -type d | sed s_./__ | sed 's_\._New Directory_' | fzf --prompt="Enter Directory: ")

    if [ "$location" = "New Directory" ]; then

        dir_name=$(zenity --name=menu --entry --text="Enter Directory Name")

        mkdir "$dir_name"

        location=$(echo $dir_name)

    fi

    entry=$(zenity --name=menu --entry --text="Enter Entry Name")

    option=$(echo -e "Generate Password\nInsert Password\nInsert Multiple Lines" | grep -i 'Generate Password\|Insert Password\|Insert Multiple Lines' | fzf --prompt="Options: ")

    if [ "$option" = "Generate Password" ]; then

         swaymsg move container scratchpad

         pass generate -n "$location"/"$entry"

         notify-send "Password succesfully generated"

         exit 0

    elif [ "$option" = "Insert Password" ]; then

        current=$(zenity --name=menu --entry --text="Enter Password")

        swaymsg move container scratchpad

        yes "$current" | pass insert -f "$location"/"$entry"

        notify-send "Password succesfully created"

        exit 0

    elif [ "$option" = "Insert Multiple Lines" ]; then

        pass edit "$location"/"$entry"

        swaymsg move container scratchpad

        notify-send "Password succesfully created"

        exit 0

    fi

    exit 1

elif [ "$option" = "Delete" ]; then

    PASSFILE=$(tree -Ffi | rg '.gpg' | sed 's/.gpg$//g' | sed 's/^..//' | fzf --prompt="Entry: ")

    pass rm "$PASSFILE"

    notify-send "Password Deleted"

    exit 0

elif [ "$option" = "Edit" ]; then

    PASSFILE=$(tree -Ffi | rg '.gpg' | sed 's/.gpg$//g' | sed 's/^..//' | fzf --prompt="Entry: ")

    edit=$(echo -e "Edit Password\nRotate\nAdd Additional Info" | grep -i 'Edit Password\|Rotate\|Add Additional Info' | fzf --prompt="Options: ")

    if [ "$edit" = "Edit Password" ]; then 

        current=$(pass show "$PASSFILE" | head -n 1)

        read -re -i "$current" -p 'Edit: ' current

        yes "$current" | pass insert -f "$PASSFILE"

        notify-send "Updated $PASSFILE"

        exit 0

    elif [ "$edit" = "Rotate" ]; then

        notify-send "Not yet supported."

        exit 0

    elif [ "$edit" = "Add Additional Info" ]; then

        pass edit "$PASSFILE"

        notify-send "Updated $PASSFILE"

        exit 0

    fi

elif [ "$option" = "Git" ]; then

    operation=$(echo -e "Update Master\nSync" | grep -i 'Update Master\|Sync' | fzf --prompt="Operation: ")

    if [ "$operation" = "Update Master" ]; then

        swaymsg move container scratchpad

        pass git push origin master

        notify-send "Remote master updated"

        exit 0

    elif [ "$operation" = "Sync" ]; then

        swaymsg move container scratchpad

        pass git pull origin master

        notify-send "Passwords synced"

        exit 0

    fi
fi

exit 1
