#!/bin/bash

bat=$(cat /sys/class/power_supply/BAT0/capacity)
if [ $bat -gt 90 ]
then
  bat_symbol="\uf240"
  color=green
elif [ $bat -gt 60 ]
then
  bat_symbol="\uf241"
  color=green
elif [ $bat -gt 40 ]
then
  bat_symbol="\uf242"
  color=yellow
elif [ $bat -gt 15 ]
then
  bat_symbol="\uf243"
  color=orange
else
  bat_symbol="\uf244"
  color=red
fi
stat=$(cat /sys/class/power_supply/BAT0/status)
charing=""
if [ "$stat" = "Charging" ]
then
  charging="<span color=\"orange\">\uf1e6  </span>"
elif [ "$stat" = "Full" ]
then
    charging="\uf1e6 (charged) "
fi

echo -e "$charging<span color=\"$color\">"$bat_symbol " "$bat"%</span>"
