#!/bin/bash
vol=$(pamixer --get-volume)
color=white
percentsign="%"
if [[ $vol -ge 25 ]]; then
	vol_symbol="\uf028"
else
	vol_symbol="\uf027"
fi
if [[ $(pamixer --get-mute) == "true" ]]; then
  vol="mute"
	vol_symbol="\uf026"
	color=red
	percentsign=""
fi

echo -e "<span color=\"$color\">$vol_symbol $vol$percentsign</span>"

if [[ $BLOCK_BUTTON == "1" ]]; then
        swaymsg exec pavucontrol
elif [[ $BLOCK_BUTTON == "2" ]]; then
        swaymsg exec blueberry
fi
